CREATE DATABASE IF NOT EXISTS sum_app;

USE sum_app;

CREATE TABLE IF NOT EXISTS calculations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    number1 DOUBLE NOT NULL,
    number2 DOUBLE NOT NULL,
    result DOUBLE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
