services:
  web:
    build: .
    container_name: sum_app_web
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: sum_app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sum_app
      MYSQL_USER: sumuser
      MYSQL_PASSWORD: 12345
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
